server:
  port: 8071
  servlet:
    context-path: /
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    in-memory: false
    #以下这句话，只在测试Topic才加，否则去除
  jms:
    pub-sub-domain: true